"""add_failure_mode_to_runs

Revision ID: 41509c4a1e21
Revises: c8002bf009a7
Create Date: 2026-03-08 02:15:33.838050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '41509c4a1e21'
down_revision: Union[str, Sequence[str], None] = 'c8002bf009a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicitly create the ENUM type for PostgreSQL before adding the column
    failure_mode_enum = postgresql.ENUM('FORMAT_ERROR', 'HALLUCINATION', 'REFUSAL', 'TRUNCATED', 'TIMEOUT', 'API_ERROR', 'CONTEXT_EXCEEDED', 'UNKNOWN', name='failure_mode')
    failure_mode_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('runs', sa.Column('failure_mode', failure_mode_enum, nullable=True))
    op.add_column('runs', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'error_message')
    op.drop_column('runs', 'failure_mode')
    # ### end Alembic commands ###
