"""Add QUEUED status and runs unique constraint

Revision ID: 76c8f0c2228a
Revises: 36be4b5ddd52
Create Date: 2026-01-02 14:21:01.327773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c8f0c2228a'
down_revision: Union[str, Sequence[str], None] = '36be4b5ddd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_runs_experiment_example', 'runs', ['experiment_id', 'example_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_runs_experiment_example', 'runs', type_='unique')
    # ### end Alembic commands ###
