"""rename input and output to prompt and raw_output

Revision ID: ff53d769bd7c
Revises: e3f2a1b0c9d8
Create Date: 2026-03-06 04:27:53.041742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff53d769bd7c'
down_revision: Union[str, Sequence[str], None] = 'e3f2a1b0c9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_experiment_id'), table_name='results')
    op.create_index(op.f('ix_results_experiment_id'), 'results', ['experiment_id'], unique=True)
    op.alter_column('runs', 'input_text', new_column_name='prompt')
    op.alter_column('runs', 'output_text', new_column_name='raw_output')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'error_message')
    op.drop_column('runs', 'failure_mode')
    op.alter_column('runs', 'raw_output', new_column_name='output_text')
    op.alter_column('runs', 'prompt', new_column_name='input_text')
    op.drop_index(op.f('ix_results_experiment_id'), table_name='results')
    op.create_index(op.f('ix_results_experiment_id'), 'results', ['experiment_id'], unique=False)
    # ### end Alembic commands ###
